ProyectoDatosEF/Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoDatosEF.Models
{
    [Table ("DOCTOR")]
    public class Doctor
    {
        [Key]
        [Column("DOCTOR_NO")]
        public int IdDoctor { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("ESPECIALIDAD")]
        public string Especialidad { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("HOSPITAL_COD")]
        public int IdHospital { get; set; }
    }
}

ProyectoDatosEF/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoDatosEF.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("OFICIO")]
        public string Oficio { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

ProyectoDatosEF/Models/ErrorViewModel.cs
namespace ProyectoDatosEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoDatosEF/Models/Hospital.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoDatosEF.Models
{
    [Table ("HOSPITAL")]
    public class Hospital
    {
        //Si hacemos consultas de accion, deberiamos tener un campo como clave (PK)
        [Key]
        [Column("HOSPITAL_COD")]
        public int IdHospital { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DIRECCION")]
        public string Direccion { get; set; }
        [Column("TELEFONO")]
        public string Telefono { get; set; }
        [Column("NUM_CAMA")]
        public int Camas { get; set; }
    }
}

ProyectoDatosEF/Models/Plantilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoDatosEF.Models
{
    [Table ("PLANTILLA")]
    public class Plantilla
    {
        [Key]
        [Column("EMPLEADO_NO")]
        public int IdEmpleado { get; set; }
        [Column("HOSPITAL_COD")]
        public int IdHospital { get; set; }
        [Column("SALA_COD")]
        public int IdSala { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("FUNCION")]
        public string Funcion { get; set; }
        [Column("T")]
        public string Turno { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
    }
}

ProyectoDatosEF/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDatosEF.Models;
using ProyectoDatosEF.Repositories;

namespace ProyectoDatosEF.Controllers
{
    public class DoctoresController : Controller
    {
        RepositoryDoctor repo;
        public DoctoresController(RepositoryDoctor repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }

        public IActionResult DoctoresHospital(int idhospital)
        {
            List<Doctor> doctores = this.repo.GetDoctoresHospital(idhospital);
            return View(doctores);
        }
    }
}

ProyectoDatosEF/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDatosEF.Models;
using ProyectoDatosEF.Repositories;

namespace ProyectoDatosEF.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;
        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }
        public IActionResult ListadoEmpleados()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            ViewData["EMPLEADOS"] = this.repo.GetFunciones();
            return View(empleados);
        }
        [HttpPost]
        public IActionResult ListadoEmpleados(string funcion, int incremento)
        {
            this.repo.IncrementarSalario(funcion, incremento);
            List<Empleado> empleados = this.repo.GetEmpleadosPorFuncion(funcion);
            ViewData["EMPLEADOS"] = this.repo.GetFunciones();
            return View(empleados);
        }

        public IActionResult Delete(int id)
        {
            Empleado emp = this.repo.FindEmpleado(id);
            return View(emp);
        }

        [HttpPost]
        public IActionResult Delete(Empleado emp)
        {
            this.repo.DeleteEmpleado(emp.IdEmpleado);
            return RedirectToAction("ListadoEmpleados");
        }
    }
}

ProyectoDatosEF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDatosEF.Models;
using System.Diagnostics;

namespace ProyectoDatosEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoDatosEF/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDatosEF.Models;
using ProyectoDatosEF.Repositories;

namespace ProyectoDatosEF.Controllers
{
    public class HospitalesController : Controller
    {
        private RepositoryHospital repo;
        public HospitalesController(RepositoryHospital repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            //Devolvemos todos los hospitales
            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }

        public IActionResult Details(int id)
        {
            Hospital hospital = this.repo.FindHospital(id);
            return View(hospital);
        }

        public IActionResult ConsultasAccion()
        {
            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }
        [HttpPost]
        public IActionResult ConsultasAccion(int idhospital,string accion)
        {

            if(accion.ToUpper() == "INSERT")
            {
                this.repo.InsertHospital(idhospital);

            }else if (accion.ToUpper() == "DELETE")
            {
                this.repo.DeleteHospital(idhospital);

            }else if (accion.ToUpper() == "UPDATE")
            {
                this.repo.UpdateHospital(idhospital);
            }
            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }
    }
}

ProyectoDatosEF/Controllers/PlantillasController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDatosEF.Models;
using ProyectoDatosEF.Repositories;

namespace ProyectoDatosEF.Controllers
{
    public class PlantillasController : Controller
    {
        RepositoryPlantilla repo;
        public PlantillasController(RepositoryPlantilla repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Plantilla> plantillaTotal = this.repo.GetPlantilla();
            return View(plantillaTotal);
        }

        public IActionResult Details(int idempleado)
        {
            Plantilla plantilla = this.repo.GetEmpleado(idempleado);
            return View(plantilla);
        }

        public IActionResult EmpleadosPlantilla(int idhospital)
        {
            List<Plantilla> listado = this.repo.GetPlantillaHospital(idhospital);
            return View(listado);
        }

        public IActionResult BuscarPlantillaPorFuncion()
        {
            List<Plantilla> plantillaTotal = this.repo.GetPlantilla();
            ViewData["FUNCIONES"] = this.repo.GetFunciones();
            return View(plantillaTotal);
        }
        [HttpPost]
        public IActionResult BuscarPlantillaPorFuncion(string funcion)
        {
            List<Plantilla> plantilla = this.repo.GetPlantillaFuncion(funcion);
            ViewData["FUNCIONES"] = this.repo.GetFunciones();
            return View(plantilla);
        }
    }
}

ProyectoDatosEF/Views/Doctores/DoctoresHospital.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Doctor>

@{
    ViewData["Title"] = "DoctoresHospital";
}

<h1>Lista de doctores en este hospital</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdDoctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Doctores/Index.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Doctor>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de doctores</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdDoctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Empleados/Delete.cshtml
@model ProyectoDatosEF.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oficio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oficio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
    </dl>
    
    <form method="post">
        <input asp-for="@Model.IdEmpleado" class="form-control" type="hidden" />
        <input asp-for="@Model.Apellido" class="form-control" type="hidden"  />
        <input asp-for="@Model.Oficio" class="form-control" type="hidden"  />
        <input asp-for="@Model.Salario" class="form-control" type="hidden" />
        <button class="btn btn-danger">Borrar</button>
    </form>
 </div>

ProyectoDatosEF/Views/Empleados/ListadoEmpleados.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Empleado>

@{
    ViewData["Title"] = "ListadoEmpleados";
    List<String> funciones = ViewData["EMPLEADOS"] as List<String>;
}

<h1>Listado de empleados</h1>

<form method="post">
    <label>Oficios:</label>
    <select name="funcion">
        @foreach (String funcion in funciones)
        {
            <option value="@funcion">@funcion</option>
        }
    </select>
    <br/>
    <label>Incremento salarial:</label>
    <input type="text" class="form-control" name="incremento" />
    <button class="btn btn-dark">Incrementar salario</button>
</form>
<hr/>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oficio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr >
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
                <td style="background-color:plum">
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                <a asp-controller="Empleados" asp-action="Delete" asp-route-id="@item.IdEmpleado">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoDatosEF/Views/Hospitales/Details.cshtml
@model ProyectoDatosEF.Models.Hospital

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHospital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHospital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Camas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Camas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ProyectoDatosEF/Views/Hospitales/Index.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Hospital>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de hospitales</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Camas)
            </td>
            <td>
                <a asp-controller="Hospitales" asp-action="Details" asp-route-id="@item.IdHospital">Detalles</a>
                <a asp-controller="Doctores" asp-action="DoctoresHospital" asp-route-idhospital="@item.IdHospital">Doctores</a>
                <a asp-controller="Plantillas" asp-action="EmpleadosPlantilla" asp-route-idhospital="@item.IdHospital">Plantilla</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Plantillas/Details.cshtml
@model ProyectoDatosEF.Models.Plantilla

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Plantilla</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHospital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHospital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSala)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSala)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Funcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Funcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
    </dl>
</div>
<div>

    <a asp-controller="Hospitales" asp-action="Index">Back to List</a>
</div>

ProyectoDatosEF/Views/Plantillas/EmpleadosPlantilla.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Plantilla>

@{
    ViewData["Title"] = "EmpleadosPlantilla";
}

<h1>EmpleadosPlantilla</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSala)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Funcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSala)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Funcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                <a asp-controller="Plantillas" asp-action="Details" asp-route-idempleado="@item.IdEmpleado">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Plantillas/Index.cshtml
@model IEnumerable<ProyectoDatosEF.Models.Plantilla>

@{
    ViewData["Title"] = "Index";
}

<h1>Plantilla</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSala)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Funcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSala)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Funcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                    <a asp-controller="Plantillas" asp-action="Details" asp-route-idempleado="@item.IdEmpleado">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoDatosEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoDatosEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoDatosEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoDatosEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitales" asp-action="Index">Hospitales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Index">Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantillas" asp-action="Index">Plantilla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantillas" asp-action="BuscarPlantillaPorFuncion">Buscar plantilla por funcion</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitales" asp-action="ConsultasAccion">Editar hospitales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="ListadoEmpleados">Listado de empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProyectoDatosEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>